import {chromium,expect} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const art=resolve('artifacts/browser');await mkdir(art,{recursive:true});
const report={status:'RUNNING',cases:[],pageErrors:[],networkRequests:[],screenshots:[]};
const check=(name,details={})=>{report.cases.push({name,passed:true,...details});console.log('PASS',name);};
const executablePath=process.env.CHROMIUM_PATH;if(!executablePath)throw Error('Set CHROMIUM_PATH to the hosted sandboxed Chrome executable');
const browser=await chromium.launch({executablePath,headless:true,chromiumSandbox:true});
report.browserVersion=browser.version();report.chromiumSandboxRequested=true;
const commands=execFileSync('ps',['-eo','args'],{encoding:'utf8'}).split('\n').filter(line=>line.includes('--remote-debugging-pipe')&&line.includes('--user-data-dir=')&&/chrome|chromium/.test(line));
if(!commands.length||commands.some(line=>line.includes('--no-sandbox')))throw Error('Sandboxed Chrome process was not established');
report.sandboxCommandVerified=true;
const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});await context.setOffline(true);
const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))report.networkRequests.push(r.url());});
const url=pathToFileURL(resolve('dist/map-parcel.html')).href;let downloads=0;page.on('download',()=>downloads++);
async function shot(name){await page.screenshot({path:resolve(art,name),fullPage:true});report.screenshots.push(name);}
async function folder(name='fixture-source'){await page.locator('#folder-input').setInputFiles(resolve('artifacts',name));await expect(page.locator('#entry')).toBeEnabled();await expect(page.locator('#status')).not.toContainText(/Reading the folder|フォルダを読み込んで/);await page.locator('#entry').selectOption('maps/selected.tmx');}
async function ready(){await expect(page.locator('#export')).toBeEnabled();await expect(page.locator('#file-count')).toHaveText('16');}
async function save(button,name,keyboard=false){const wait=page.waitForEvent('download');if(keyboard){await page.locator(button).focus();await page.keyboard.press('Enter');}else await page.locator(button).click();const download=await wait;await download.saveAs(resolve(art,name));return readFile(resolve(art,name));}
try{
 await page.goto(url);await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('#export')).toBeDisabled();await shot('01-ja-empty-desktop.png');check('Offline HTML opens in Japanese with export blocked');
 await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#workspace')).toBeFocused();check('Keyboard skip link focuses workspace');
 const chooserWait=page.waitForEvent('filechooser');await page.locator('#folder-input').focus();await page.keyboard.press('Enter');const chooser=await chooserWait;await chooser.setFiles(resolve('artifacts/fixture-source'));await expect(page.locator('#entry')).toBeEnabled();await page.locator('#entry').selectOption('maps/selected.tmx');await ready();check('Keyboard folder picker imports a real directory');await expect(page.locator('#path-list li')).toHaveCount(16);await expect(page.locator('#path-list')).toContainText('art/ground/sprite.png');await expect(page.locator('#path-list')).toContainText('art/objects/sprite.png');await expect(page.locator('#excluded-count')).toHaveText('4');await shot('02-ja-folder-desktop.png');
 const zip=await save('#export','browser-selected.zip',true);const receipt=JSON.parse((await save('#receipt','browser-receipt.json')).toString());
 expect(receipt.entry).toBe('maps/selected.tmx');expect(receipt.files).toHaveLength(16);expect(receipt.zip.sha256).toBe(createHash('sha256').update(zip).digest('hex'));const oracle=JSON.parse(await readFile('test/expected-oracle.json','utf8'));expect(receipt.files.map(file=>file.path)).toEqual(oracle.paths);for(const file of receipt.files)expect(file.sha256).toBe(oracle.hashes[file.path]);check('Actual folder import and keyboard ZIP download preserve exact path/hash oracle',{zipSHA256:receipt.zip.sha256,bytes:zip.length});
 await page.locator('#lang-en').click();await expect(page.locator('html')).toHaveAttribute('lang','en');await ready();await expect(page.locator('#entry')).toHaveValue('maps/selected.tmx');await shot('03-en-reviewed-desktop.png');check('Language switch preserves folder, selected entry and receipt');
 await page.locator('#supplements summary').click();const note=page.locator('#supplement-list input[data-path="NOTICE-assets.txt"]');await expect(note).not.toBeChecked();await note.check();await expect(page.locator('#file-count')).toHaveText('17');await expect(page.locator('#receipt')).toBeDisabled();await save('#export','browser-with-supplement.zip');await save('#receipt','browser-supplement-receipt.json');check('Supplement is excluded by default, explicit opt-in adds one file and invalidates prior receipt');await page.locator('#supplement-list input[data-path="NOTICE-assets.txt"]').uncheck();await ready();
 for(const language of ['ja','en']){
  await page.locator(`#lang-${language}`).click();await save('#export',`review-${language}.zip`);await page.emulateMedia({media:'print'});await page.pdf({path:resolve(art,`review-${language}.pdf`),format:'A4',printBackground:true,preferCSSPageSize:true});await page.emulateMedia({media:'screen'});
  for(const width of [390,320]){await page.setViewportSize({width,height:844});const bounds=await page.evaluate(()=>({view:innerWidth,scroll:document.documentElement.scrollWidth}));expect(bounds.scroll).toBeLessThanOrEqual(bounds.view+1);await shot(`04-${language}-mobile-${width}.png`);}
 }
 check('Japanese/English print PDFs and 390/320px mobile reviews have no page overflow');await page.setViewportSize({width:1440,height:1100});
 await page.locator('#lang-en').click();
 const initial=await page.locator('#folder-summary').textContent();await page.locator('#folder-input').setInputFiles([]);await expect(page.locator('#folder-summary')).toHaveText(initial);await ready();check('Empty/cancelled folder selection preserves the existing valid review');
 for(const [name,code] of [['missing','MISSING_FILE'],['outside','ROOT_ESCAPE'],['class-default','CLASS_DEFAULTS'],['case-collision','PATH_COLLISION'],['malformed','INVALID_XML'],['fragmented','AMBIGUOUS_FILE_VALUE']]){await folder('browser-inputs/'+name);await expect(page.locator('#status')).toContainText(code);await expect(page.locator('#export')).toBeDisabled();await expect(page.locator('#receipt')).toBeDisabled();check(`Real folder ${name} blocks ZIP and stale receipt`);}
 await shot('05-en-blocked.png');
 await page.evaluate(()=>{window.__arrayBuffer=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){await new Promise(resolve=>setTimeout(resolve,700));return window.__arrayBuffer.call(this);};});
 await page.locator('#folder-input').setInputFiles(resolve('artifacts/fixture-source'));await expect(page.locator('#status')).toContainText('Reading');await page.locator('#sample').click();await ready();await page.waitForTimeout(1000);await expect(page.locator('#folder-summary')).toContainText('sample');await ready();check('Late folder read cannot overwrite a newer sample');
 await page.locator('#folder-input').setInputFiles(resolve('artifacts/fixture-source'));await expect(page.locator('#status')).toContainText('Reading');await page.locator('#reset').click();await page.waitForTimeout(1000);await expect(page.locator('#results')).toBeHidden();await expect(page.locator('#export')).toBeDisabled();await expect(page.locator('#status')).toContainText('cleared');check('Clear cancels pending file reads without reviving results');await page.evaluate(()=>File.prototype.arrayBuffer=window.__arrayBuffer);
 await page.locator('#sample').click();await ready();await page.evaluate(()=>{window.__digest=crypto.subtle.digest.bind(crypto.subtle);crypto.subtle.digest=async(...args)=>{await new Promise(resolve=>setTimeout(resolve,700));return window.__digest(...args);};});
 const before=downloads;await page.locator('#export').click();await expect(page.locator('#export')).toBeDisabled();await page.locator('#entry').selectOption('metamaps/mini.tmx');await expect(page.locator('#file-count')).toHaveText('2');await page.waitForTimeout(1000);expect(downloads).toBe(before);await expect(page.locator('#receipt')).toBeDisabled();check('Entry change cancels pending export and prevents stale downloads');await page.evaluate(()=>crypto.subtle.digest=window.__digest);
 await folder();await ready();await save('#export','browser-repeated-1.zip');await save('#export','browser-repeated-2.zip');expect(await readFile(resolve(art,'browser-repeated-1.zip'))).toEqual(await readFile(resolve(art,'browser-repeated-2.zip')));check('Repeated completed export is byte-deterministic');
 const offline=await save('#offline','saved-offline.html');expect(offline.toString()).not.toContain('fixture-source ·');const reopened=await context.newPage();reopened.on('pageerror',e=>report.pageErrors.push(e.message));reopened.on('request',r=>{if(/^https?:/.test(r.url()))report.networkRequests.push(r.url());});await reopened.goto(pathToFileURL(resolve(art,'saved-offline.html')).href);await expect(reopened.locator('#export')).toBeDisabled();await expect(reopened.locator('#folder-summary')).toHaveText('まだ選ばれていません');await reopened.locator('#sample').click();await expect(reopened.locator('#file-count')).toHaveText('16');await reopened.close();check('Saved offline HTML reopens offline without prior user state');
 expect(report.pageErrors).toEqual([]);expect(report.networkRequests).toEqual([]);report.status='PASS';
}finally{await writeFile(resolve(art,'browser-report.json'),JSON.stringify(report,null,2)+'\n');await context.close();await browser.close();}
console.log(`PASS ${report.cases.length} browser scenarios; actual downloads are ready for independent/native checks`);
